//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo0910.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Gender { get; set; }

        public System.DateTime Birthday { get; set; }

        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
    
        public virtual EmployeeData EmployeeData1 { get; set; }
        public virtual EmployeeData EmployeeData2 { get; set; }
        public virtual EmployeeData EmployeeData11 { get; set; }
        public virtual EmployeeData EmployeeData3 { get; set; }
    }

 

}
