//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo0910.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using demo0910.Models;

    [Serializable]//[ser] 
    public partial class UnitTable
    {
        public int UnitNO { get; set; }
        public string UnitName { get; set; }
        public int EmployeeID { get; set; }
        public string JobTitle { get; set; }
        public int seniority { get; set; }
    
        public virtual UnitTable UnitTable1 { get; set; }
        public virtual UnitTable UnitTable2 { get; set; }
        public virtual UnitTable UnitTable11 { get; set; }
        public virtual UnitTable UnitTable3 { get; set; }


        //public UnitTable(int unitno, string unitname, int employeeid, string jobtitle, int Seniority)
        //{
        //    this.UnitNO = unitno;
        //    this.UnitName = unitname;
        //    this.EmployeeID = employeeid;
        //    this.JobTitle = jobtitle;
        //    this.seniority = Seniority;

        //}

    }
}
